[supervisord]
nodaemon=true

[program:backend]
directory=/app/backend
command=uvicorn api.main:app --host 0.0.0.0 --port 8005
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:sandbox]
directory=/app/sandbox
command=uvicorn main:app --host 0.0.0.0 --port 8001
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:frontend]
directory=/app/frontend
command=npm run preview -- --host 0.0.0.0 --port 5173
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
